// <auto-generated />
using BusinessLogic.FileMonitor.FileDescriptor.FileDescriptorIndexer.EFCore.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessLogic.FileMonitor.FileDescriptor.FileDescriptorIndexer.EFCore.Migrations
{
    [DbContext(typeof(FileDescriptorContext))]
    [Migration("20230624183708_RecyclerDBInitialMigration")]
    partial class RecyclerDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.18");

            modelBuilder.Entity("BusinessLogic.FileMonitor.FileDescriptor.FileDescriptorIndexer.EFCore.Entities.FileDescriptorEntity", b =>
                {
                    b.Property<string>("FullPath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeInfoType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("FullPath");

                    b.ToTable("FileDescriptors");
                });
#pragma warning restore 612, 618
        }
    }
}
